### ISSUE TITLE
这个必须要@某人吗？，能否直接输入QQ号？

### ISSUE THREAD

**Issue by 1055169799** [BeiYazi0/fake_news#1]
如果@了某人，那破绽就很明显了，而且像12345这种不在群里的QQ号也没法@，装逼就失败了

**Comment by BeiYazi0** [comment]
可以不at某人，也可以直接获取不在群的成员的昵称，但是我认为这样似乎不太好，这个伪造的消息记录感觉有点真，可能会骗到人，不通知被伪造的人似乎不太好，因此暂时没有这方面改进的想法。
