### ISSUE TITLE
标记消息似乎不能标记语音？

### ISSUE THREAD

**Issue by 1055169799** [BeiYazi0/fake_news#2]
标记为普通消息发送失败，标记为特殊消息直接无反应![Screenshot_2023-04-04-23-20-54-05_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://user-images.githubusercontent.com/41286675/229840259-04b876c2-009f-44cc-97d9-17bcdd9cfdca.jpg)

![Screenshot_2023-04-04-23-21-05-37_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://user-images.githubusercontent.com/41286675/229840271-525491f1-6aa2-47b2-95be-32c818a61d5e.jpg)

![Screenshot_2023-04-04-23-21-33-67_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://user-images.githubusercontent.com/41286675/229840290-621d6429-e3e5-4405-b91e-718ce9b40e71.jpg)

**Comment by BeiYazi0** [comment]
1. 标记特殊消息不能使用回复，直接发送“标记特殊消息x”等待bot回复，按提示操作即可。
2. 确保gocq能够下载语言，否则即使特殊标记也无法获取。
3. 录音只能通过标记特殊消息来标记，通过"测试标记消息x"可以获取到经过特殊标记的录音消息，但是无法在合并节点消息中显示，实际上将录音消息转发的结果是“[语言]”。
